image: byrnedo/alpine-curl

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: bash install-elm.sh
  command: source ~/.bashrc && elm reactor --port 3000

vscode:
  extensions:
    - sbrink.elm@0.25.0:h8iVStxxJZSYYScO6RJfpg==